csiDriver:
  # should be globally unique for a given cluster
  name: "org.democratic-csi.nfs"
  fsGroupPolicy: File

# add note here about volume expansion requirements
storageClasses:
  - name: freenas-nfs-csi
    defaultClass: true
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: nfs
    mountOptions:
      - noatime
      - nfsvers=4
    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
      node-publish-secret:
      controller-expand-secret:

volumeSnapshotClasses: []

driver:
  config:
    driver: freenas-nfs
    instance_id:
    httpConnection:
      protocol: http
      host: <insert-NAS-IP-Address-here>
      port: 80
      username: root
      password: <root-password
      allowInsecure: true
    sshConnection:
      host: <insert-NAS-IP-Address-here>
      port: 22
      username: root
      password: <root-password>
    zfs:
      datasetParentName: hdd/k8s/nfs/vols
      detachedSnapshotsDatasetParentName: hdd/k8s/nfs/snaps
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: 0
      datasetPermissionsGroup: 0

    nfs:
      shareHost: <insert-NAS-IP-Address-here>
      shareAlldirs: false
      shareAllowedHosts: []
      shareAllowedNetworks: []
      shareMaprootUser: root
      shareMaprootGroup: wheel
      shareMapallUser: ""
      shareMapallGroup: ""