name: traefik-custom
version: v1.0.0
description: Traefik Chart to install custom configurations in a cluster that has Traefik pre-installed
home: https://github.com/markbrown87/devops-helm
maintainers:
- name: Mark Brown
  email: mark.brown8790+devops-helm@gmail.com
  url: https://github.com/markbrown87