# Not very customizable currently
ingressRoute:
  url: home-assistant.example.com
  service:
    name: home-assistant
    port: 8080

homeAssistant:
  env:
    - name: TZ
      value: "America/New_York"

  persistence:
    enabled: true