{{- if .Values.config.enabled }}
apiVersion: v1
data:
  traefik-config.yaml: |
  http:
    routers:
{{- range $i, $value := .Values.config.routers }}
{{ $value | toYaml | indent 6 }}
{{- end }}
    services:
{{- range $i, $value := .Values.config.services }}
{{ $value | toYaml | indent 6 }}
{{- end }}
    middlewares:
{{- range $i, $value := .Values.config.middlewares }}
{{ $value | toYaml | indent 6 }}
{{- end }}
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: kube-system
{{- end }}