apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
    {{- if .Values.config.enabled }}
    - --providers.file.filename=/data/traefik-config.yaml
    {{- end }}
    - --entrypoints.websecure.http.tls.certresolver={{ .Values.provider.selection }}
    - --entrypoints.websecure.http.tls.domains[0].main={{ .Values.provider.domain }}
    - --entrypoints.websecure.http.tls.domains[0].sans=*.{{ .Values.provider.domain }}
    - --certificatesresolvers.cloudflare.acme.dnschallenge.provider={{ .Values.provider.selection }}
    - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers={{ .Values.provider.resolvers }}
    {{- if .Values.persistance.enabled }}
    - --certificatesresolvers.cloudflare.acme.storage=/certs/acme.json
    {{- end }}
    - --serversTransport.insecureSkipVerify=true
    ports:
      web:
        redirectTo:
          port: websecure
    env:
      - name: CF_DNS_API_TOKEN # or CF_API_KEY, see for more details - https://doc.traefik.io/traefik/https/acme/#providers
        valueFrom:
          secretKeyRef:
            key: apiKey
            name: cloudflare-apikey-secret
      - name: CF_API_EMAIL
        valueFrom:
          secretKeyRef:
            key: email
            name: cloudflare-apikey-secret
    ingressRoute:
      dashboard:
        enabled: false
    {{- if .Values.persistance.enabled }}
    persistence:
      enabled: true
      existingClaim: acme-json-certs
      accessMode: ReadWriteOnce
      size: 128Mi
      path: /certs
    {{- end }}
    {{- if .Values.config.enabled }}
    volumes:
      - mountPath: /data
        name: traefik-config
        type: configMap
    {{- end }}
