{{- if .Values.persistance.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acme-json-certs
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteMany # I needed both for rw
  - ReadWriteOnce # I needed both for rw
  resources:
    requests:
      storage: {{ .Values.persistance.size }}  
{{- end }}