apiVersion: v1
kind: Service
metadata:
  name: olivetin
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 1337
    protocol: TCP
    targetPort: 1337
  selector:
    app: olivetin
  type: ClusterIP